# Configuration file for MegaLinter
#
# See all available variables at https://megalinter.io/latest/config-file/ and in
# linters documentation

# all, none, or list of linter keys
APPLY_FIXES: all

# If you use ENABLE variable, all other languages/formats/tooling-formats will
# be disabled by default
# ENABLE:

# If you use ENABLE_LINTERS variable, all other linters will be disabled by
# default
# ENABLE_LINTERS:

DISABLE:
  # - COPYPASTE # Uncomment to disable checks of excessive copy-pastes
  - SPELL # Uncomment to disable checks of spelling mistakes

DISABLE_LINTERS:
  - SPELL_LYCHEE
  - REPOSITORY_CHECKOV
  - JAVASCRIPT_ES # Disable MegaLinter's bundled ESLint v8, use local v9 instead

SHOW_ELAPSED_TIME: true

# ESLint v9+ flat config support - use local installation
JAVASCRIPT_ES_FILE_EXTENSIONS:
  - .js
  - .jsx
JAVASCRIPT_ES_CLI_LINT_MODE: list_of_files
JAVASCRIPT_ES_FILTER_REGEX_EXCLUDE: (node_modules|dist|build)
# Uncomment if you want MegaLinter to detect errors but not block CI to pass
# DISABLE_ERRORS: true
